@startuml
title 4-Connect - Sprachauswahl (Wireframe)
salt
{
  {+
    {^ "Sprache" }
    ( ) English (EN)
    ( ) Deutsch (DE)
    ( ) Francais (FR)
    ( ) Espanol (ES)
    ( ) Arabic (AR)
    ( ) Chinese (ZH)
    { }
    {[ OK ]} | {[ Abbrechen ]}
  }
}
@enduml
