@startuml
title 4-Connect - Ergebnis (Wireframe)

skinparam defaultFontName Monospaced

salt
{
  {+
    { **Ergebnis** }
    .
    { **Spielende:** }
    { < "Spieler 1 gewinnt" / "Spieler 2 gewinnt" / "Bot gewinnt" / "Unentschieden" > }
    .
    {[ Neue Runde ] | [ Spielesammlung ]}
  }
}
@enduml
