@startuml Spielansicht
title 4-Connect - Spielansicht (Wireframe)

skinparam defaultFontName Monospaced

salt
{
  {+
    {^ **Vier Gewinnt**}
.
    {
    o o o o o o o
    o o o o o o o
    o o o o o o o
    o o o o o o o
    o o o o o o o
    o o o o o o o
    
    } {} {} {} {} {} {} {} {} {} {} {} { 
      
      **Am Zug:** 
      < "Spieler 1" / "Spieler 2" >
      .
      [ Zurücksetzen ]
      [Hilfe / Regeln]
      [   Hauptmenü  ]
    }
    .
  }
}
@enduml
