@startuml
title 4-Connect - Hauptmenü (Wireframe)

skinparam defaultFontName Monospaced

salt
{
  {+
    {^ **Hauptmenü** }
    .
    { **Spielauswahl** }
    {[ 4-Connect ]}{[    Spiel 2    ]}{[ Spiel 3 ]}{[ Spiel 4 ]}
    {[  Spiel 5  ]}{[    Spiel 6    ]}{[ Spiel 7 ]}{[ Spiel 8 ]}
    .
    {[    Help   ]}{[ Einstellungen ]}{         }{[ Beenden ]}
  }
}
@enduml
