@startuml Gewinnkombination
title 4-Connect - Gewinnkombination (Wireframe)

skinparam defaultFontName Monospaced

salt
{
  {+
    { **Gewinnkombination anzeigen                                   **}
.
.
    {
    o o  o  o  o  o  o
    o o  o  o  o  o  o
    o o [o] o  o  o  o
    o o  o [o] o  o  o
    o o  o  o [o] o  o
    o o  o  o  o [o] o
    }
.
.
    {[  Zurück  ]}
.
  }
}
@enduml