@startuml Ergebnis
title 4-Connect - Ergebnis (Wireframe)

skinparam defaultFontName Monospaced

salt
{
  {+
    { **Ergebnis** }
.
.
    { **< "Spieler 1 gewinnt" / "Spieler 2 gewinnt" / "Bot gewinnt" / "Unentschieden" >** }
.
.
.
    {[Gewinnkombination anzeigen] | [Neue Runde] | [Hauptmenü]}
.
  }
}
@enduml
