@startuml Modusmenü
title 4-Connect - Modusmenü (Wireframe)

skinparam defaultFontName Monospaced

salt
{
  {+
    {^ **Modusauswahl** }
.
.
    {[ Zwei Spieler ]}{[Gegen einfachen Bot]}{[Gegen schweren Bot]}
.
.
.
    {                }{                     }{[     Hauptmenü    ]}
.
  }
}
@enduml
