@startuml FourConnect_3_9_3

skinparam packageStyle rectangle
skinparam classAttributeIconSize 0
skinparam linetype ortho

' ──────────────────────────────────────────
package "Infrastructure" {

  class BrandingService {
    - {static} instance: BrandingService
    - primaryColour: String
    - secondaryColour: String
    - logoPath: String
    - airlineName: String

    - <<create>> BrandingService()
    + setTheme(themeId : String) : void
    + {static} getInstance(): brandingService
    + getPrimaryColour(): String
    + getSecondaryColour(): String
    + getLogoPath(): String
    + getAirlineName(): String
    + setPrimaryColour(primaryColour: String):void
    + setSecondaryColour(secondaryColour: String): void
    + setLogoPath(logoPath:String): void
    + setAirlineName(airlineName: String): void

  }

  class LocalizationService {
    - {static} instance: LocalizationService
    - {static} BUNDLE_BASE: String
    - bundle: ResourceBundle
    - currentLocale: Locale

    - <<create>> LocalizationService()
    + {static} getInstance(): LocalizationService
    - loadBundle(): void
    + getString(key : String): String
    + setLocale(locale: Locale): void
    + getCurrentLocale(): Locale
    + getAvailableLocales(): Locale[]
    + setLanguage(languageCode : String) : void
    + getText(key : String) : String
  }
}

' ──────────────────────────────────────────
package "FourConnect"{
 class FourConnectRules{
  }

  class FourConnectGame {
    - state : GameState
    - players : FourConnectPlayer[]
    - currentPlayerIndex : int
    - rules : FourConnectRules
    - gameBoard : FourConnectGameBoard
    - currentBranding : BrandingService
    - oneBotPlayer: boolean
    <<create>> FourConnectGame()
    + getPlayers(): FourConnectPlayer[]
    + endGame(): void
    + dropDisc(column : Integer) : GameState
    + getOneBotPlayer(): boolean
    + playerTurn() : void
    + playBotTurn() : GameState
    + initFourConnectGame(playerOne : Player, playerTwo : Player) : Integer
  }

  class FourConnectGameBoard {
    - {static} ROW_COUNTS : Integer
    - {static} COLUMN_COUNTS : Integer
    - cells : Map
    + «create» FourConnectGameBoard()
    + getRows() : Integer
    + getColumns() : Integer
    + getCellOwner(x : Integer, y : Integer) : FourConnectPlayer
    + getCellOwner(position : Position) : FourConnectPlayer
    + setCellValue(cell : Position, currentPlayer : FourConnectPlayer) : void
    + copy(board : FourConnectGameBoard) : void
  }

  class Position {
    - x : Integer
    - y : Integer
    + «create» Position(x : Integer, y : Integer)
    + getX() : Integer
    + getY() : Integer
    + equals(o : Object) : boolean
    + hashCode() : int
  }

  enum Player <<enumeration>> {
    HUMAN
    EASYBOT
    HARDBOT
    NONE
  }

  class FourConnectPlayer {
    - type : Player
    - strategy : IMoveStrategy
    - colour : String
    + «create» FourConnectPlayer(type : Player, strategy : IMoveStrategy, colour : String)
    + getType() : Player
    + getStrategy() : IMoveStrategy
    + getColour() : String
  }

class FourConnectBotStrategy {
  ~ fcGame: FourConnectGame
  ~ fcRules: FourConnectRules
  - randNum: Random
  - {static} player: Player
  - {static} bot: Player
  - {static} SCORE_BOT_FOUR: int
  - {static} SCORE_BOT_THREE: int
  - {static} SCORE_BOT_TWO: int
  - {static} SCORE_BOT_ONE: int
  - {static} SCORE_OPP_FOUR: int
  - {static} SCORE_OPP_THREE: int
  - {static} SCORE_OPP_TWO: int
  - {static} SCORE_OPP_ONE: int
  - {static} MINIMAX_DEPTH: int
  + FourConnectBotStrategy(game: FourConnectGame, rules: FourConnectRules)
  ~ appraiseBoard(board: FourConnectGameBoard): Integer
  ~ allFourConnects(board: FourConnectGameBoard): ArrayList<Position[]>
  }

  class "EasyBotStrategy" as Easy {
  }

  class "HardBotStrategy" as Hard {
    - findBestTurn(boardC: FourConnectGameBoard, depth: int): Integer
    - minMax(board: FourConnectGameBoard, depth: int, isMaximizing: boolean): Integer
    - findValideTurns(board: FourConnectGameBoard): List<Position>
    - playTestTurn(board: FourConnectGameBoard, turn: Position, currentFCPLayer: FourConnectPlayer): void
    - undoTestTurn(board: FourConnectGameBoard, turn: Position): void
    - findBotPlayerPosition(players: FourConnectPlayer[]): Integer
  }

  enum GameMode <<enumeration>> {
    TWOPLAYER
    BOT
  }
    Position     - FourConnectGameBoard
    FourConnectBotStrategy +-- Easy   : inner
    FourConnectBotStrategy +-- Hard   : inner

    FourConnectBotStrategy ..|> IMoveStrategy
    Easy ..|> IMoveStrategy
    Hard ..|> IMoveStrategy
}


package "Game Core" {

  interface IRuleSet <<interface>> {
    + checkWin(board : IPlayArea, player : PlayerT) : Boolean
    + checkTie(board : IPlayArea) : Boolean
  }

  enum GameState <<enumeration>> {
    NotStarted
    Running
    Paused
    Finished
    Won
    Tied
  }

  interface IPlayArea <<interface>> {
    + isFull() : Boolean
    + clear() : Integer
  }

  interface IMoveStrategy <<interface>> {
    + chooseMove(board : IPlayArea) : void
  }

  interface IGame <<interface>> {
    + setStatus() : void
    + restart() : void
    + getStatus() : GameState
    + getBoard() : IPlayArea
  }



  ' Realizations
  FourConnectRules      ..|> IRuleSet
  FourConnectGame       ..|> IGame
  FourConnectGameBoard  ..|> IPlayArea
  FourConnectBotStrategy ..|> IMoveStrategy

  ' Compositions / associations inside Game Core
  FourConnectGame "1" *--> "*"    FourConnectPlayer
  FourConnectGame      *-->        FourConnectRules
  FourConnectGame      *-->        FourConnectGameBoard
  FourConnectPlayer "1" o--> "0..1" FourConnectBotStrategy
}

' ──────────────────────────────────────────
package "UIController" {


  class MainMenuController {
    + startGame() : void
    + openSetting() : void
    + openHelp() : void
    + exit() : void
  }

  class HelpController {
    + backToGameScreen() : void
  }

  class ModeMenuController{
    + startGame() : void
    + startGameEasyBot() : void
    + startGameHardBot() : void
    + backToMainMenu() : void
  }

  class SettingsController {
    - languageBox : ComboBox<String>
    - localizationService : LocalizationService
    - brandingService : BrandingService
    + changeLanguage(languageCode : String) : void
    + changeTheme(themeId : String) : void
    + backToMainMenu() : void
    + initialize() : void
  }

  interface GameController <<interface>> {
    + restartGame() : void
    + backToMainMenu() : void
    + openHelp() : void
  }

  class EndScreenController{
    - resultLabel : Label
    + initialize() : void
    + restartGame() : void
    + backToMainMenu : void
  }

  }

  ' ──────────────────────────────────────────
  ' Cross-package dependencies
  SettingsController        ..> LocalizationService  : «use»
  SettingsController        ..> BrandingService       : «use»



package "UIGameController"{

  class FourConnectGameController {
    + handleColumnInput(column : Integer) : void
    + handlePlayMode( playerOne : Player, playerTwo : Player) void
    + resumeGame() : void
    - initBoard() : void
    - updateBoard() : void
    - updateStatus() : void
  }
     ' Cross-package dependencies
         FourConnectGameController ..|> GameController
         FourConnectGameController ..> FourConnectGame       : «use»

 }


@enduml
