@startuml
title 4-Connect – Sequenzdiagramm Spielzug ausführen

skinparam defaultFontName Monospaced
skinparam ParticipantPadding 80
skinparam BoxPadding 50

skinparam SequenceLifeLineBorderColor #666666
skinparam SequenceLifeLineBackgroundColor transparent
skinparam SequenceArrowThickness 1

skinparam ResponseMessageBelowArrow true

actor "              Fluggast              " as Fluggast
|||
boundary "              FourConnectGameController              " as Controller
|||
control "              FourConnectGame              " as Game


Fluggast -> Controller : handleColumnInput(column)

Controller -> Game : dropDisc(column)
Game --> Controller : GameState

Controller -> Controller : updateBoard()
|||

alt GameState == Won
  Controller -> Controller : updateStatus()
else GameState == Tied
  Controller -> Controller : updateStatus()
else GameState == Running
  Controller -> Game : getOneBotPlayer()
  Game --> Controller : boolean
  |||

  alt Bot-Modus aktiv
    Controller -> Game : playBotTurn()
    Game --> Controller : GameState

    Controller -> Controller : updateBoard()
    |||

    alt GameState == Won
      Controller -> Controller : updateStatus()
      |||
    else GameState == Tied
      Controller -> Controller : updateStatus()
      |||
    else GameState == Running
      Controller -> Controller : updateStatus()
      |||
    end

  else Zwei-Spieler-Modus
    Controller -> Controller : updateStatus()
    |||
  end
end
|||


@enduml
