@startuml
title 4-Connect – Anwendungsfalldiagramm

left to right direction

skinparam defaultFontName Monospaced
skinparam linetype ortho
skinparam ArrowThickness 1
skinparam ArrowColor #444444
skinparam dashedLineColor #666666
skinparam nodesep 200
skinparam ranksep 400
skinparam padding 30
skinparam defaultTextAlignment left

skinparam ResponseMessageBelowArrow true


actor "   Fluggast   " as Fluggast
actor "   Fluggesellschaft   " as Airline

rectangle "4-Connect" {
  usecase "Spiel auswählen" as UC1
  usecase "Spielmodus wählen" as UC2
  usecase "Spiel spielen" as UC3
  usecase "Neue Runde starten" as UC4
  usecase "Hilfe Hauptmenü öffnen" as UC12
  usecase "Spielhilfe öffnen" as UC5
  usecase "Einstellungen öffnen" as UC6
  usecase "Sprache auswählen" as UC7
  usecase "Zurück zum Hauptmenü" as UC8
  usecase "Branding konfigurieren" as UC9
  usecase "Ergebnis anzeigen" as UC10
  usecase "Gewinnkombination anzeigen" as UC11
}


Fluggast --> UC1
Fluggast --> UC12
Fluggast --> UC6


Airline --> UC9


UC1 ..> UC2 : <<include>>

UC2 ..> UC3 : <<include>>

UC6 ..> UC7 : <<include>>


UC3 --> UC10 : [Sieg oder Unentschieden erkannt]

UC4 ..> UC3 : <<extend>>\n[Während des Spiels ausgewählt]\nExtension Point: InGameMenu

UC4 ..> UC10 : <<extend>>\n[Im Ergebnis ausgewählt]\nExtension Point: Endscreen

UC5 ..> UC3 : <<extend>>\n[Hilfe ausgewählt]\nExtension Point: InGameMenu

UC8 ..> UC12 : <<extend>>\n[Hauptmenü ausgewählt]\nExtension Point: Navigation

UC8 ..> UC6 : <<extend>>\n[Hauptmenü ausgewählt]\nExtension Point: Navigation

UC8 ..> UC2 : <<extend>>\n[Hauptmenü ausgewählt]\nExtension Point: Navigation

UC8 ..> UC3 : <<extend>>\n[Hauptmenü ausgewählt]\nExtension Point: Navigation

UC8 ..> UC10 : <<extend>>\n[Hauptmenü ausgewählt]\nExtension Point: Endscreen

UC11 ..> UC10 : <<extend>>\n[Button ausgewählt]\nExtension Point: Endscreen


@enduml