@startuml
title 4-Connect – Sequenzdiagramm Spielzug ausführen

skinparam defaultFontName Monospaced
skinparam ParticipantPadding 80
skinparam BoxPadding 50

skinparam SequenceLifeLineBorderColor #666666
skinparam SequenceLifeLineBackgroundColor transparent
skinparam SequenceArrowThickness 1

skinparam ResponseMessageBelowArrow true

actor "       Fluggast       " as Fluggast
|||
boundary "       FourConnectGameController       " as Controller
|||
control "       FourConnectGame       " as Game
|||
entity "       FourConnectPlayer       " as Player
|||
control "       FourConnectBotStrategy       " as Strategy
|||
control "       App       " as App

Fluggast -> Controller : handleColumnInput(column)

Controller -> Game : dropDisc(column)
Game --> Controller : GameState

Controller -> Controller : updateBoard()
|||

alt GameState == Won
  Controller -> App : setRoot("EndScreen")
|||
else GameState == Tied
  Controller -> App : setRoot("EndScreen")
|||
else GameState == Running
  Controller -> Game : playerTurn()
  Controller -> Controller : updateStatus()
|||

  alt Bot-Spieler aktiv

    Controller -> Game : getPlayers()
    Game --> Controller : FourConnectPlayer[]

    Controller -> Player : getStrategy()
    Player --> Controller : strategy

    Controller -> Strategy : chooseMove(board)
    Strategy -> Game : dropDisc(botColumn)
    Game --> Strategy : GameState

    Strategy--> Controller: GameState

    Controller -> Controller : updateBoard()
    |||
    alt GameState == Won
      Controller -> App : setRoot("EndScreen")
    |||
    else GameState == Tied
      Controller -> App : setRoot("EndScreen")
    |||
    else GameState == Running
      Controller -> Game : playerTurn()
      Controller -> Controller : updateStatus()
      |||
    end
    |||
  end
  |||
end
|||
|||

@enduml
