@startuml
title 4-Connect - Aktivitätsdiagramm Spielrunde

skinparam defaultFontName Monospaced
skinparam linetype ortho
skinparam nodesep 300
skinparam ranksep 300
skinparam padding 10

start

:Spielzustand initialisieren;
:Spielbrett anzeigen;

repeat
  :Aktuellen Spieler anzeigen;
  :Spielzug eingeben;
  :Spielzug validieren;

  if ([Zug gültig?]) then ([ja])
    :Spielstein platzieren;
    :Spielbrett aktualisieren;

    if ([Gewinnbedingung erfüllt?]) then ([ja])

      repeat
        :Ergebnis anzeigen;

        if ([Gewinnkombination anzeigen gewählt?]) then ([ja])
          :Spielbrett erneut anzeigen;
          :Gespeicherte Gewinnkombination laden;
          :Gewinnbringende Spielsteine hervorheben;
          :Zurück zum Ergebnis;
        elseif ([Neue Runde gewählt?]) then ([ja])
          :Spielzustand neu initialisieren;
          :Spielbrett anzeigen;
          stop
        else ([Hauptmenü gewählt])
          :Zurück zur Spielesammlung;
          stop
        endif

      repeat while ([Weitere Aktion im Endscreen?]) is ([ja])

    else ([nein])

      if ([Spielfeld voll?]) then ([ja])
        :Unentschieden anzeigen;

        if ([Neue Runde gewählt?]) then ([ja])
          :Spielzustand neu initialisieren;
          :Spielbrett anzeigen;
          stop
        else ([Hauptmenü gewählt])
          :Zurück zur Spielesammlung;
          stop
        endif

      else ([nein])
        :Spieler wechseln;
      endif

    endif

  else ([nein])
    :Fehlermeldung anzeigen;
  endif

repeat while ([Spiel nicht beendet?]) is ([ja])

@enduml