@startuml
title 4-Connect – Anwendungsfalldiagramm

left to right direction

skinparam defaultFontName Monospaced
skinparam linetype ortho
skinparam ArrowThickness 1
skinparam ArrowColor #444444
skinparam dashedLineColor #666666
skinparam nodesep 200
skinparam ranksep 400
skinparam padding 30
skinparam defaultTextAlignment left

skinparam ResponseMessageBelowArrow true


actor "   Fluggast   " as Fluggast
actor "   Fluggesellschaft   " as Airline

rectangle "4-Connect" {
  usecase "Spiel starten" as UC1
  usecase "Spielmodus wählen" as UC2
  usecase "Spiel spielen" as UC3
  usecase "Neue Runde starten" as UC4
  usecase "Spielhilfe anzeigen" as UC5
  usecase "Einstellungen öffnen" as UC6
  usecase "Sprache auswählen" as UC7
  usecase "Zurück zur Spielesammlung" as UC8
  usecase "Branding konfigurieren" as UC9
  usecase "Gewinnkombination anzeigen" as UC10
}

Fluggast --> UC1
Fluggast --> UC2
Fluggast --> UC3
Fluggast --> UC4
Fluggast --> UC5
Fluggast --> UC6
Fluggast --> UC7
Fluggast --> UC8

Airline --> UC9


UC6 ..> UC7 : <<include>>
UC3 ..> UC4 : <<extend>>\n[Spiel beendet]\nExtension Point: Endscreen
UC3 ..> UC5 : <<extend>>\n[Hilfe ausgewählt]\nExtension Point: InGameMenu
UC3 ..> UC6 : <<extend>>\n[Einstellungen ausgewählt]\nExtension Point: InGameMenu
UC3 ..> UC8 : <<extend>>\n[Spiel beendet oder Abbruch]\nExtension Point: Navigation
UC3 ..> UC10 : <<extend>>\n[Gewinn erkannt]\nExtension Point: GameFinished

@enduml
